# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/dma_data_ram/dma_data_ram.xci
# IP: The module: 'dma_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/dma_data_ram/dma_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/dma_data_ram/dma_data_ram.xci
# IP: The module: 'dma_data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/dma_data_ram/dma_data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dma_data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
