@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1.3 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Tue Aug 02 16:34:26 -0700 2022
REM SW Build 2644227 on Wed Sep  4 09:45:24 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 67c347176b0f4b6a94702a60dc120ade --incr --debug typical --relax --mt 2 -L wavis_lib -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_dmaSignalsGenerator_behav xil_defaultlib.tb_dmaSignalsGenerator xil_defaultlib.glbl -log elaborate.log"
call xelab  -wto 67c347176b0f4b6a94702a60dc120ade --incr --debug typical --relax --mt 2 -L wavis_lib -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm --snapshot tb_dmaSignalsGenerator_behav xil_defaultlib.tb_dmaSignalsGenerator xil_defaultlib.glbl -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
