# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/PCIe_IP.xci
# IP: The module: 'PCIe_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/source/PCIe_IP-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIe_IP'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/synth/PCIe_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIe_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/PCIe_IP.xci
# IP: The module: 'PCIe_IP' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/source/PCIe_IP-PCIE_X0Y0.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIe_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/mcassinerio/Documents/GitHub/HTGK7-NRCA-DMA/HTGK7-NRCA-DMA.srcs/sources_1/ip/PCIe_IP/synth/PCIe_IP_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PCIe_IP'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
